name: release

on:
  push:
    branches: [ "main" ]
jobs:
  setup:
    name: setup
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
      - uses: pnpm/action-setup@v2.2.2
      - name: キャッシュのリストア
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: install dpendencies
        run: pnpm i --frozen-lockfile

  build:
    name: build
    runs-on: ubuntu-20.04
    needs: setup
    steps:
      - name: restore node modules
        id: cache-node-modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml') }}
      - name: check build
        run: pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: apexTaimanCounter
          path: _release
      - uses: actions/upload-pages-artifact@v1
        with:
          path: packages/web-application/out

  deploy:
    runs-on: ubuntu-latest 
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/deploy-pages@v1
        id: deployment

