name: CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    name: build
    runs-on: ubuntu-20.04
    steps:

      - uses: actions/checkout@v4

      - name: Install PNPM
        uses: pnpm/action-setup@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"

      - name: install dpendencies
        run: pnpm i --frozen-lockfile

      - name: check build
        run: pnpm run build


  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - uses: actions/upload-artifact@v3
        with:
          name: apexTaimanCounter
          path: _release

      - uses: actions/upload-pages-artifact@v1
        with:
          path: packages/web-application/out

      - uses: actions/deploy-pages@v1
        id: deployment

